### ISSUE TITLE
文档 404 问题

### ISSUE THREAD

**Issue by GuangChen2333** [Lunova-Studio/MinecraftLaunch#1]
https://www.blessingta.link/minecraftlaunch/

出现问题的文档有
https://www.blessingta.link/minecraftlaunch/utils/modrinth.html
https://www.blessingta.link/minecraftlaunch/utils/java.html
https://www.blessingta.link/minecraftlaunch/utils/modpack.html
https://www.blessingta.link/minecraftlaunch/utils/save.html
https://www.blessingta.link/minecraftlaunch/utils/resourcepack.html
https://www.blessingta.link/minecraftlaunch/analyzers.html
https://www.blessingta.link/minecraftlaunch/authenticators/microsoft.html

**Comment by GuangChen2333** [comment]
此外 本仓库给出的文档 如
https://baka_hs.gitee.io/xilu-baka/2022/12/29/MinecraftLaunch%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A33/
等缺少一部分组件的文档 望完善

**Comment by ZhiFengCode** [comment]
文档其实也不能算是出现问题报404，只不过是还没写而已他们（

**Comment by GuangChen2333** [comment]
🤔
