### ISSUE TITLE
新大功能！

### ISSUE THREAD

**Issue by Rwagsu** [Lunova-Studio/MinecraftLaunch#2]
做一个方法，这个方法会检查Mod兼容性，文件完整性，服务器Mod兼容性，显卡兼容性，Java等各种潜在或存在的错误，分类，返回几个错误，警告的列表，比如检查Mod兼容性，文件完整性，服务器Mod兼容性，显卡兼容性，Java等各种潜在或存在的错误，分类，返回几个错误，警告的列表

**Comment by Rwagsu** [comment]
至于要检查什么，我等回去填（

**Comment by YangSpring114** [comment]
ok了
