### ISSUE TITLE
网站*完全*无法访问

### ISSUE THREAD

**Issue by AXCWG** [Lunova-Studio/MinecraftLaunch#3]
https://www.blessingta.link/

**Comment by Orange-Icepop** [comment]
> https://www.blessingta.link/

![image](https://github.com/user-attachments/assets/22746f29-caaf-40b8-a6dd-85856fba5a25)
我这里检测到DNS解析已经被修改，指向了一个非法地址，不知道开发团队在干神马，希望能快点恢复（哭）要不然我就得自己写一个了

**Comment by Rwagsu** [comment]
（最近好忙一点电脑没看QAQ）
看起来是域名寄了，不过域名只是打开了blessing-studio.github.io的内容（也就是说域名只是为了美观（bushi）），目前你可以直接访问blessing-studio.github.io，内容和blessingta.link一样（

**Comment by Orange-Icepop** [comment]
> （最近好忙一点电脑没看QAQ） 看起来是域名寄了，不过域名只是打开了blessing-studio.github.io的内容（也就是说域名只是为了美观（bushi）），目前你可以直接访问blessing-studio.github.io，内容和blessingta.link一样（

感谢回复！
我在发布了上一条回复那时的第二周就尝试访问了blessing-studio.github.io并发现其内容就是原来的blessingta.link，但是忘了在此issue下方进行再次回复（大悲）

**Comment by Rwagsu** [comment]
> > （最近好忙一点电脑没看QAQ） 看起来是域名寄了，不过域名只是打开了blessing-studio.github.io的内容（也就是说域名只是为了美观（bushi）），目前你可以直接访问blessing-studio.github.io，内容和blessingta.link一样（
> 
> 感谢回复！
> 我在发布了上一条回复那时的第二周就尝试访问了blessing-studio.github.io并发现其内容就是原来的blessingta.link，但是忘了在此issue下方进行再次回复（大悲）

c我刚问了，域名是换新的了（
新域名是https://wiki.blessing-studio.cn/
⊙ω⊙

**Comment by dream-pep** [comment]
十分抱歉，由于文档库被dream_pep❤️搞崩了
然后又被dream_pep❤️就活了
所以我们将文档从原先的域名https://wiki.blessing-studio.cn/
迁移至https://wiki.blessing-studio.tech/
非常感谢各位的支持，注意变更文档地址

**Comment by dream-pep** [comment]
十分抱歉，由于文档库被dream_pep❤️搞崩了
然后又被dream_pep❤️就活了
所以我们将文档从原先的域名https://wiki.blessing-studio.cn/
迁移至https://wiki.blessing-studio.tech/
非常感谢各位的支持，注意变更文档地址
